from pathlib import Path
from datetime import datetime,timezone,timedelta
import hashlib,json,re
root=Path(__file__).resolve().parents[2];mp=root/'manifest.json';manifest=json.loads(mp.read_text())
new={'07G1_HUB_SETTINGS','07G2_LOCAL_WORLDS','07H4_BOT_ENGINE','07P5_POSE_CANVAS','07P6_STUDIO_SETS','09A2_PREVIEW_LAYOUT','09C6_AVATAR_PREVIEW','09C7_COMMUNITY_FEED','09C8_COMMUNITY_DETAILS','09B1_AVATAR_DISCOVERY','09B2_COSPLAY_METADATA'}
locals={'07G_HUB_UI','07H_GAME_UI','07P_PHOTO_MODE','09C_SHOP_CLIENT'}
servers={'09B_SHOP_SERVER'};server_modules={'09B1_AVATAR_DISCOVERY','09B2_COSPLAY_METADATA'}
order=['07G2_LOCAL_WORLDS','07G1_HUB_SETTINGS','07H4_BOT_ENGINE','07P5_POSE_CANVAS','07P6_STUDIO_SETS','09A2_PREVIEW_LAYOUT','09C6_AVATAR_PREVIEW','09C7_COMMUNITY_FEED','09C8_COMMUNITY_DETAILS','09B2_COSPLAY_METADATA','09B1_AVATAR_DISCOVERY','07UI_DESIGN_SYSTEM','07UI_SCREEN_BOUNDS','07P0_STUDIO_PRESETS','07P3_POSE_EDITOR','07P2_STUDIO_AVATAR','07P4_STUDIO_UI','09A1_SHOP_LAYOUT','09A_SHOP_UI','09C4_OUTFIT_LIBRARY','09C2_SHOP_CATALOG','09C1_SHOP_LOOKS','09B_SHOP_SERVER','07G_HUB_UI','07H_GAME_UI','07P_PHOTO_MODE','09C_SHOP_CLIENT']
assert len(order)==27 and set(order)=={p.stem for p in(root/'scripts/V43').glob('*.lua')}
specs=[];sources={}
for name in order:
 path='scripts/V43/'+name+'.lua';code=(root/path).read_text();n=len(code.splitlines());assert n<=400 and not re.search(r'(?:\+|-|\*|/|\.\.)=',code)
 specs.append(dict(name=name,type='LocalScript'if name in locals else'Script'if name in servers else'ModuleScript',location='StarterPlayer > StarterPlayerScripts'if name in locals else'ServerScriptService'if name in servers or name in server_modules else'ReplicatedStorage',action='CRIAR'if name in new else'SUBSTITUIR',lines=n,sha256=hashlib.sha256(code.encode()).hexdigest(),path=path,parts=4 if name=='09A_SHOP_UI'else 2,hide_full=name=='09A_SHOP_UI'));sources[path]=code
version=dict(id='V43',title='MANEQUIM DE POSE + COMUNIDADE VIRTUAL + CONFIGURAÇÕES',date='2026-10-03',summary='Configurações com categorias coloridas e cinco mundos visuais locais. Photo Mode com manequim 2D arrastável, Aplicar/Cancelar sem rolagem e cinco cenários animados. Plus abre diretamente o plano oficial. Catálogo exibe 5 × 4 cards em celular deitado e computador; telas verticais se adaptam. Meus looks tem prévia maior e cards menores. Comunidade consulta usuários reais do Roblox, recicla até 50 cards e prepara páginas ao avançar; detalhes opacos trazem giro 360°, itens com X, preços e autoria. Bots com níveis distintos em xadrez, damas e treino de memória da batata. Fechamentos maiores e protegidos contra respostas atrasadas.',install_note='Requer a V42 completa já instalada, incluindo 08B_AVATAR_DATA e 08D_SKIN_STATE V41, regras 07A0/07B0, 07P1_CAPTURE_ENGINE e 08L_COMMUNITY existentes. Pare Play. CRIE os 11 módulos indicados: nove em ReplicatedStorage e 09B1_AVATAR_DISCOVERY/09B2_COSPLAY_METADATA em ServerScriptService. SUBSTITUA os outros 16 scripts nos locais indicados, sem duplicar instâncias. Para 09A_SHOP_UI, apague o código antigo uma vez e cole exatamente as 4 partes em ordem no MESMO ModuleScript. Instale os 27 itens antes do próximo Play. Plus usa o plano oficial sem game pass ou página intermediária. A Comunidade tem capacidade de até 1 milhão de registros paginados, não uma base de 1 milhão já verificada. Referências de cosplay são inferências conservadoras dos nomes de camisa e calça consultados no Roblox; reconhecimento visual universal exige serviço externo.',validation='27 scripts com sintaxe verificada, até 400 linhas e sem atribuição composta. 27 casos funcionais/sintaxe com Lua 5.4 e serviços simulados, incluindo layouts, prévias em quatro ângulos, preservação da skin, captura/fechamento, bots e reciclagem de páginas nativas/publicadas. Instalador verificado com seu JavaScript real, hashes e remontagem exata das partes. Layouts inspecionados em cinco resoluções por imagens aproximadas. Falta teste no Studio Lite/Roblox para renderização 3D, toque real, respostas/rate limits dos serviços, assinatura e captura nativas.',scripts=specs)
manifest['latest']='V43';manifest['updated_at']=max(datetime.now(timezone.utc),datetime.fromisoformat(manifest['updated_at'])+timedelta(seconds=1)).isoformat(timespec='seconds')
manifest['versions']=[v for v in manifest['versions']if v['id']!='V43']+[version];mp.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
fallback=dict(manifest,versions=[version]);js=(Path(__file__).parent/'installer_runtime.js').read_text()
def safe(value):return json.dumps(value,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c').replace('\u2028','\\u2028').replace('\u2029','\\u2029')
constants='const REPO_OWNER="kauanlindo44",REPO_NAME="avatar-plaza-script-hub",BRANCH="main";\nconst RAW=`https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}`;\nconst FALLBACK_MANIFEST='+safe(fallback)+';\nconst FALLBACK_SCRIPTS='+safe(sources)+';\n'
hp=root/'AVATAR_PLAZA_SCRIPT_HUB_PERMANENTE.html';html=hp.read_text();html=re.sub(r'<script>[\s\S]*?</script>',lambda _: '<script>\n'+constants+js+'\n</script>',html);html=re.sub(r'inclui a V\d+(?:\.\d+)?','inclui a V43',html);hp.write_text(html)
print(json.dumps(dict(latest=manifest['latest'],scripts=len(specs),new=len(new),replacements=len(specs)-len(new),max_lines=max(s['lines']for s in specs),html_bytes=hp.stat().st_size),ensure_ascii=False))
